---
title: "Lab 3"
author: "Zach Schroeder, Kavya Mudiam, Praleigh Goodwin, Ann Marie Barrett, Vinita Vader"
date: "2/3/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rio)
library(here)
library(janitor)
library(gghighlight) 
library(cowplot)
library(colorspace)
library(colorblindr)
library(ggtext)
# library(dplyr) # shouldn't need this becuase it's part of tidyverse
#remotes::install_github("hrbrmstr/albersusa")
library(albersusa)
library(scales)
# library(forcats) # same as above

# Note you had a small typo below (you had "tb_df" instead of "tbl_df")
data <- import(here("data", "honeyproduction.csv"), setclass = "tbl_df") %>% 
  characterize() %>% 
  clean_names()

data_region <- import(here("data", "censusregions.csv"), setclass = "tbl_df") %>% 
  characterize() %>% 
  clean_names()

```

# Question 1
```{r warning=FALSE}
plot1 <- data %>% 
  mutate(Year = factor(year), 
         Totalprod = as.numeric(totalprod)) %>% 
  select(state, Totalprod, Year) %>% 
 # as_tibble() %>% 
  ggplot(aes(Year, Totalprod, group = state)) +
  geom_line(aes(color = state))+
  facet_wrap(~state, scales = "free_y", ncol = 1) +
  gghighlight(state == c("WA", "OR", "CA"),
              unhighlighted_colour = alpha("#bcbddc", 0.4)) + 
  scale_color_OkabeIto() +
  labs(y = "Total production",
       title = "Total production of honey across years by state") +
  geom_hline(aes(yintercept = 0), color= "#636363", size = .2) +
  # scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) + #stop scientific notation
  # rather than the above, I would do
  scale_y_continuous(labels = scales::comma) +
  theme_minimal()

plot1 + theme(panel.grid.minor = element_blank(), 
              panel.background = element_blank(),
              plot.title = element_text(size = 11, face = "bold", hjust = 0.5),
              axis.ticks = element_line(color = "#bdbdbd"),
              axis.title.x = element_text(size = 11, face = "bold"),
              axis.title.y = element_text(size = 11, face = "bold"),
              axis.text.x = element_markdown(hjust = 1))


plot1_nofacet <- data %>% 
  mutate(Year = factor(year), 
         Totalprod = as.numeric(totalprod)) %>% 
  select(state, Totalprod, Year) %>% 
  #as_tibble() %>% 
  ggplot(aes(Year, Totalprod, group = state)) +
  geom_line(aes(color = state)) +
  gghighlight(state == c("WA", "OR", "CA"),
              unhighlighted_colour = alpha("#e7d1c1", 0.5)) + 
  scale_color_OkabeIto() +
  labs(y = "Total production",
       title = "Total production of honey across years by state") +
  geom_hline(aes(yintercept = 0), color = "#636363", size = .2) +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_minimal() + 
  theme(panel.grid.minor = element_blank(), 
             panel.background = element_blank(),
             plot.title = element_text(size = 8, face = "bold", hjust = 0.5),
              axis.ticks = element_line(color = "#bdbdbd"),
             axis.title.x = element_text(size = 8, face = "bold"),
             axis.title.y = element_text(size = 8, face = "bold"),
             axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=.5))
plot1_nofacet

# The only thing I'd say about the above is that the hline at zero is 
# overlapping the OR logo (in certain aspect ratios), so you might swap the 
# order of those so the label is on top. I'd also swap the y labels as I 
# showed above


```

# Question 2
```{r warning=FALSE}
colorblindr::cvd_grid(plot1_nofacet)
```

# Question 3
```{r, warning=FALSE}
# I stopped styling here
plot_cb <- data %>% 
  mutate(Year = factor(year), 
  Totalprod = as.numeric(totalprod))%>% 
  select(state, Totalprod, Year) %>% 
  as_tibble() %>% 
  ggplot(aes(Year, Totalprod, group = state)) +
    geom_line(aes(color = state))+
   gghighlight(state == c("WA", "OR", "CA"),
               unhighlighted_colour = alpha("#e7d1c1", 0.5)) + 
  scale_fill_viridis_d()+ #color-blind safe
  labs(y = "Total production",
       title = "Total production of honey across years by state")+
    geom_hline(aes(yintercept = 0), color= "#636363", size = .2)+
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE))+ 
  theme_minimal() +
  theme(panel.grid.minor = element_blank(), 
             panel.background = element_blank(),
             plot.title = element_text(size=8, face="bold", hjust = 0.5),
              axis.ticks = element_line(color = "#bdbdbd"),
             axis.title.x = element_text(size=8, face="bold"),
             axis.title.y = element_text(size=8, face="bold"),
             axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=.5))
plot_cb


colorblindr::cvd_grid(plot_cb)
#the green and blue is a bit hard to differentiate in the Tritanomaly version, however, I think it's different enough. Just might not be ideal. 

#safe_colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499","#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")
#scales::show_col(safe_colorblind_palette)
```

# Question 4
```{r}
data_honey <- data %>% 
  mutate(state_code = state) %>% 
  select(-state)
  
data_honey2 <- left_join(data_honey, data_region, by = "state_code")


data_honey2 %>% 
  group_by(region) %>% 
  summarise(mean = mean(totalprod))

data_honey2 %>% 
  ggplot() + 
  geom_bar(aes(totalprod, fct_reorder(state, totalprod), fill = region),
         stat = "summary", fun.x = "mean",
         alpha = .8,
         position = "dodge",
         color = "white") +
  scale_x_log10(labels = comma) +
  coord_cartesian(xlim = c(100000, 100000000)) +
  labs(x = "Average Honey Production (lbs)", y = "State", fill = "Region",
       title = "Midwest and West Dominate US Honey Production") +
   theme_minimal() +
  scale_fill_OkabeIto(order = c(2,5,7,8))+
  theme(panel.grid.major.y = element_blank(),
        plot.title = element_text(size=17),
        axis.title.x = element_text(size=13),
        axis.title.y = element_text(size=13),
        axis.text = element_text(size=8))

# Ooh... I like that color palette
```

# Question 5
```{r}

data_honey_3 <- data_honey2 %>% 
  group_by(region, year) %>% 
  summarise(honey = mean(totalprod))

data_honey_3 %>% 
  ggplot(aes(year, region)) +
  geom_tile(aes(fill = honey),
            color = "white") +
  coord_fixed() +
  scale_fill_viridis_c() +
  labs(x = "Year", y = "Region", fill = "Honey", 
       title = "Regional Honey Production (lbs) Across Years") +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        plot.title = element_text(size=17),
        axis.title.x = element_text(size=13),
        axis.title.y = element_text(size=13),
        axis.text = element_text(size=8))

# Very nice! You might also consider putting the legend on the bottom or the
# on the top so it can be horizontal (giving more space for the actual plot)
```

# Question 6
```{r}
# Creating same column names for joining
us <- usa_sf() %>% 
  mutate(
    state = factor(name))

data_honey2 <- data_honey2 %>% 
  mutate(
    state = factor(state)
  )

# Creating total production summary variable to join back to US data
df <- data_honey2 %>%
  group_by(state) %>% 
  summarise(.groups = "keep",
    tprod = mean(totalprod, na.rm = T)
  )
data_map <- left_join(us, df, by = "state")

# Plot
ggplot(data_map) +
  geom_sf(aes(fill = tprod)) +
    scale_fill_viridis_c(option = "plasma") +
  labs(title = "Total Honey Production by State",
       fill = "Total Honey\nProduction",
       caption = "Grey states did not provide data")

# Beautiful! Really well done.
```

